type = "card"
title = "Blog"
description = "Random thoughts and notes from life and work."

[[items]]
title = "一人食火锅 😋"
image = "/blog/hotpot.jpg"
date = "2026-04-25"
location = "中国 北京"
content = "一人食火锅😋"
