[[experience]]
logo = "/logos/pku.svg"
school = "Peking University (PKU)"
date = "2023.09 - Present"
role = "Undergraduate Student"
major = "Major: Intelligence Science and Technology (Artificial Intelligence)"
